server:
  port: 8080

spring:
  application:
    name: franchise-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/franchise_db}

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/franchise_db}

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://root:secret@mongo:27017/franchise_db?authSource=admin

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/franchise_db_test

---
spring:
  config:
    activate:
      on-profile: no-mongo
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: inmem
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveRepositoriesAutoConfiguration
