services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: franchise_db
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchise-api
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SERVER_PORT: "8080"
      SPRING_PROFILES_ACTIVE: docker
      # IMPORTANT: Use SPRING_DATA_MONGODB_URI (exact name), not MONGODB_URI
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/franchise_db?authSource=admin
    ports:
      - "8080:8080"

volumes:
  mongo_data:
